{% set setup_py = load_setup_py_data() %}

package:
    name: 'scratchnet'
    version: {{ setup_py.get('version') }}

source:
    path: ./

build:
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    run:
        - python >=3.5
        - matplotlib
        - numpy
    build:
        - python
        - setuptools

about:
    license: {{ setup_py.get('license') }}
    license_file: LICENSE
    summary: {{ setup_py.get('description') }}
